myapp/urls.py
from django.urls import path
from django.conf.urls import url
from django.urls import include
from myapp import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm


app_name = 'myapp'

urlpatterns = [
path(r'', views.index, name='index'),
path(r'about/' , views.about, name='about'),
path(r'detail/<int:cat_no>/', views.detail,name='detail'),
path(r'products/', views.products, name='products'),
path(r'place_order/', views.place_order, name='place_order'),
path(r'products/<int:prod_id>/', views.productdetail, name='product detail'),
path(r'login/', views.user_login, name='login'),
path(r'logout/', views.user_logout, name='logout'),
path(r'myorders/', views.myorders, name='myorders'),
path(r'register/', views.register, name='register'),
path(r'reset-password/', password_reset, name='reset_password'),
path(r'reset-password/done/', password_reset_done, name='password_reset_done'),
path(r'reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/', password_reset_confirm, name='password_reset_confirm'),
]

mysiteS18/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
    path(r'myapp/', include('django.contrib.auth.urls')),
]

myapp/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

# Create your models here.
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=200)
    warehouse = models.CharField(max_length=30, null=False, blank=False, default='Windsor')

    def __str__(self):
        return self.name+", "+self.warehouse


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=100,validators=[MaxValueValidator(1000),MinValueValidator(0)])
    available = models.BooleanField(default=True)
    description = models.TextField(null=True, blank=True)
    interested = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def refill(self, prodname):
        product = Product.objects.get(name=prodname)
        product.stock = product.stock + 100
        product.save()
        return self.stock


class Client(User):
    PROVINCE_CHOICES = [
        ('AB', 'Alberta'),
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'),
    ]

    company = models.CharField(max_length=50,  null=True, blank=True)
    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province=models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    interested_in = models.ManyToManyField(Category)



class Order (models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    num_units = models.PositiveIntegerField(default=0)
    order_status = [
        (0, 'Order Cancelled'),
        (1, 'Order Placed'),
        (2, 'Order Shipped'),
        (3, 'Order Delivered'),
    ]
    status_date = models.DateField

    def __str__(self):
        return str(self.client)

    def total_cost(self):
        return Product.price*int(self.num_units)

myapp/forms.py
from django import forms
from myapp.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('product', 'client', 'num_units')
        # fields = ('product', 'num_units')
        widgets = {
            'client': forms. RadioSelect(attrs={'class': 'radio'}),
        }
        labels = {
            'client': "Client Name",
            'num_units': "Quantity",
        }


class InterestForm(forms.Form):
    interested = forms.BooleanField(widget=forms.RadioSelect(choices=[(1, 'Yes'), (0, 'No')]))
    quantity = forms.IntegerField(initial=1)
    comments = forms.CharField(label='Additional Comments', widget=forms.Textarea, required=False)


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'required': True, 'class': 'validate', 'placeholder': 'Username'}), label="")
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'required': True, 'class': 'validate input-field', 'placeholder': 'Password'}),
        label="")

myapp/views.py
import datetime
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404,reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test



# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from .models import Category, Product, Client, Order
from .forms import  *

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        user = request.user

    else:
        user = ""
    cat_list = Category.objects.all().order_by('id')
    return render(request, 'myapp/index.html', {'cat_list': cat_list, 'user': user})


def about(request):

    response = render(request, 'myapp/about.html')  # store the response in response variable
    if not request.COOKIES.get('about_visits'):
        response.set_cookie('about_visits', '1', 300)
    else:
        about_visits = int(request.COOKIES.get('about_visits', '1')) + 1
        response.set_cookie('about_visits', str(about_visits), 300)
    return response


def detail(request,cat_no):
    category = get_object_or_404(Category, id=cat_no)
    product_name = category.products.all()
    return render(request, "myapp/detail.html", {'cat_no':cat_no,'category':category,'product' :product_name})


def products(request):
    prodlist = Product.objects.all().order_by('id')
    return render(request, 'myapp/products.html', {'prodlist': prodlist})


def place_order(request):
    msg = ''
    neg = 0
    if request.user.is_authenticated:
        testuser = request.user
        prodlist = Product.objects.all()
        if request.method == 'POST':
            form = OrderForm(request.POST)
            if form.is_valid():
                order = form.save(commit=False)
                if order.num_units <= order.product.stock:
                    product = Product.objects.get(name=order.product.name)
                    product.stock = product.stock - order.num_units
                    product.save()
                    msg = 'Your order has been placed successfully.'
                    neg = 0
                    pd = Product()
                    pd.refill(order.product.name)
                    order.save()
                else:
                    neg = 1
                    msg = 'We do not have sufficient stock to fill your order.'
                return render(request, 'myapp/order_response.html', {'msg': msg, 'neg': neg})
        else:
            form = OrderForm()
            return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'prodlist': prodlist,'testuser':testuser})
    else:
        testuser = ""
        msg = 'You need to be logged in first!'
        request.session.set_test_cookie()
        return HttpResponseRedirect(reverse('myapp:login'))


def productdetail(request, prod_id):
    msg = ''
    prod_list = Product.objects.get(id=prod_id)
    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            if request.POST['interested'] == '1':
                prod = Product.objects.get(id=prod_id)
                prod.interested += 1
                prod.save()
                msg = 'Your interest is updated successfully.'
            else:
                msg = 'Your interest is not updated successfully.'
        return render(request, 'myapp/index.html', {'form': form, 'prod_list': prod_list, 'msg': msg})
    else:
        form = InterestForm()
        return render(request, 'myapp/productdetail.html', {'form': form, 'prod': prod_list, 'msg': msg})


def user_login(request):
    form = LoginForm()
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        cli = Client.objects.get(username=username)
        user = authenticate(request, username=username, password=password)
        request.session.set_expiry(3600)
        if user:
            if user.is_active:
                if 'last_login' in request.session:
                    last_login = request.session.get('last_login')
                else:
                    currentDT = datetime.datetime.now()
                    request.session['last_login'] = str(currentDT.strftime("%d-%m-%Y %H:%M"))
                login(request, user)
                if request.session.get('frommyorder'):
                    del request.session['frommyorder']
                    return HttpResponseRedirect(reverse('myapp:myorders'))
                elif request.session.test_cookie_worked():
                    request.session.delete_test_cookie()
                    prodlist = Product.objects.all()
                    # return render(request, 'myapp/placeorder.html', {'prodlist': prodlist })
                    return HttpResponseRedirect(reverse('myapp:place_order'))
                else:
                    return HttpResponseRedirect(reverse('myapp:index'))
                #return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled')
        else:
            msg = "Invalid login details."
            return render(request, 'myapp/login.html', {'msg': msg})
    else:
        return render(request, 'myapp/login.html')


@login_required()
def user_logout(request):
    logout(request)
    msg = "You successfully logged out"
    cat_list = Category.objects.all().order_by('id')
    return render(request, 'myapp/index.html', {'msg': msg, 'cat_list': cat_list})


def myorders(request):
    if request.user.is_authenticated:
        testuser = request.user
        myorder = Order.objects.filter(client__username=request.user)
        return render(request, 'myapp/myorders.html', {'myorder': myorder, 'testuser': testuser})

    else:
        testuser = ""
        message = 'login please'
        request.session['frommyorder'] = True
        return HttpResponseRedirect(reverse('myapp:login'))


def register(request):
    if request.method == 'POST':
        msg=''
        print(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        company=request.POST.get('company')
        shipping_address=request.POST.get('shippingadd')
        city=request.POST.get('city')
        province=request.POST.get('prov')
        print(request.POST)
        print(username, password)
        client=Client.objects.create(username=username, password=password, company=company, shipping_address=shipping_address,city=city,province=province,is_superuser=True,is_staff=True)
        msg='Registered successfully'
        return render(request, 'myapp/index.html', {'msg': msg})
    else:
        return render(request, 'myapp/register.html')

templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <div class="panel panel-info indexpanel1">
        <div class="panel-heading"><h1>This is an Online Store APP</h1></div>
        <div class="panel-body">
             Canadian retail company which sells a wide range of electronics, Furniture, Appliances,Home Decor and leisure. Some stores also sell toys and food products. The company's head office is in Toronto, Ontario. The retailer is known for its  money, a loyalty program first introduced in 1958, where customers are provided with coupons resembling paper money worth 0.4% of their purchase that can be used in subsequent purchases as scrip at Our Online stores.
        </div>
        <div class="panel-footer">
            {% if not request.COOKIES.about_visits %}
                This is your first visit.
            {% else %}
                You have visited this page {{ request.COOKIES.about_visits|add:'1' }} times.
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/myapp/about0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>

<body>
    <p><h1>  This is an Online Store APP </h1></p>
    <p><a href="/myapp/">Go back Home</a></p>
    <p><a href="{% url 'myapp:index' %}">Go back Home</a></p>
</body>
</html>

templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
    <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-inverse" style="margin-bottom: 0">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'myapp:index' %}"><i class="fas fa-shopping-basket"></i> The Online Store</a>
          </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li ><a href="{% url 'myapp:index' %}">Home </a></li>
                    <li><a href="{% url 'myapp:about' %}">About</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li ><a href="{% url 'myapp:products' %}">List All Products</a></li>
                            <li ><a href="{% url 'myapp:place_order' %}">Place New Order</a></li>
                         </ul>
                    </li>
                </ul>
              <h4 class="message navbar-text usernamething">{% block myhdg %}Hello {{ request.user.username | upper }}  {% endblock %}</h4>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{%  url 'myapp:myorders' %}"> View Your Orders <i class="fas fa-shopping-cart"></i> </a></li>
                    <li><a href="{% url 'myapp:logout' %}"> Log Out <i class="fas fa-user-times"></i> </a></li>
                {% else %}
                    <li><a href="{% url 'myapp:login' %}">Log In <i class="fas fa-user"></i> </a></li>
                    <li><a href="{% url 'myapp:register' %}"> Register <i class="fas fa-user-plus"></i> </a></li>
                {% endif %}
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
<div>
    {% block body_block%}***{% endblock %}
</div>
<script
        src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
{#<script src="{% static 'myapp/store.js' %}"></script>#}
</body>
</html>

templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
 {% if category %}
     <div class="panel panel-success detailpanel">
        <!-- Default panel contents -->
        <div class="panel-heading">
            Category :  {{ category.name}}  <br>
            Warehouse Location :  {{ category.warehouse}}
        </div>

        <!-- Table -->
        <table class="table">
            <tr class="">
                <th>#</th>
                <th>Product</th>
            </tr>
            {% for pro  in product%}
                <tr>
                    <td class="counterCell"></td>
                    <td>{{ pro}}</td>
                </tr>
            {% endfor%}
        </table>
    </div>


{#<b>  Category :  {{ category.name}}  <br>#}
{#     Warehouse Location :  {{ category.warehouse}}   <br>#}
{#        Products: </b> <br>#}
{##}
{##}
{##}
{#<ol>#}
{#            {% for pro  in product%}#}
{#<li> {{ pro}} </li>#}
{#{% endfor%}#}
{#</ol>#}

    {% else %}
<strong>There are no available categories! </strong>
    {% endif %}



{% endblock %}

templates/myapp/detail0.html
{#{% extends 'myapp/base.html' %}#}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>

<body>

 {% if category %}
<b>  Category :  {{ category.name}}  <br>
     Warehouse Location :  {{ category.warehouse}}   <br>
        Products: </b> <br>



<ol>
            {% for pro  in product%}
<li> {{ pro}} </li>
{% endfor%}
</ol>

    {% else %}
<strong>There are no available categories! </strong>
    {% endif %}


<p><a href="{% url 'myapp:index' %}">Go back to Main</a></p>

</body>
</html>

templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load staticfiles %}

{% block myhdg %}
    Hello {{ request.user.username  | upper}}
{% endblock %}

{% block body_block %}
    <div class="jumpbthing" >
        <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div id="content">
                    <h1 class="storetitle">The Online Store</h1>
                    <hr>
                    <h3>The One Place To Shop</h3>
                </div>
            </div>
        </div>
    </div>
    </div>
    {% if msg %}
        <div class="alert alert-success" role="alert"><h4>{{ msg }}</h4></div>
    {% endif %}
    {% if cat_list%}
        <div class="panel panel-info indexpanel">
        <!-- Default panel contents -->
            <div class="panel-heading"><h3 class="panel-title">List of Categories</h3></div>
            <!-- List group -->
            <ul class="list-group">
                {% for cat  in cat_list%}
                    <li class="list-group-item"><a href="{% url 'myapp:detail' cat.id %}">{{ cat.name}} </a></li>
                {% endfor%}
            </ul>
            <div class="panel-footer">
                {% ifnotequal request.session.last_login None %}
                    <h4><b>Last Login: </b>{{ request.session.last_login }}</h4>
                {% else %}
                    <h4><b>Last Login: </b>Your last login was more than one hour ago</h4>
                {% endifnotequal %}
            </div>
        </div>
    {% else %}
        <div class="alert alert-warning" role="alert"><strong>There are no available categories!</strong></div>
    {% endif %}
{% endblock %}

templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Online Store APP</title>
</head>

<body>
    {% if cat_list %}
        <h2>List of Categories</h2>
        <ol>
            {% for cat  in cat_list %}
                <li> {{ cat.name}} </li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}
    <p><a href="/myapp/about">About page</a></p>
</body>
</html>

templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block body_block %}

<form method="post">
{% csrf_token %}
    {% if msg %}
        <div class="alert alert-danger" role="alert"><h4>{{ msg }}</h4></div>
    {% endif %}
    <div class="loginform">
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1">@</span>
            <input type="text" name="username" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
        </div>
        <div class="input-group">
            <span class="input-group-addon" id="basic-addon1"><i class="fas fa-key"></i></span>
            <input type="password" name="password" class="form-control" placeholder="Password" aria-describedby="basic-addon1">
        </div>
        <button type="submit" value="submit" class="btn btn-success loginbtn">Login</button>
        <a href="{% url 'myapp:reset_password' %}">forgot password?</a>
    </div>
</form>
{% endblock %}

templates/myapp/myorders.html
{% extends 'myapp/base.html' %}

{% block body_block %}

{% if testuser.client %}

    {% if myorder %}
        <div class="panel panel-success detailpanel">

            <table class="table">
            <tr class="thisrow">

                <th>#</th>
                <th>Product</th>

            </tr>
            {% for order in myorder %}
                <tr>
                    <td class="counterCell"></td>
                    <td>{{ order.product }}</td>
                </tr>
            {% endfor %}
            </table>
        </div>

    {% else %}
        <div class="alert alert-info" role="alert"><strong>You have not placed any order!</strong></div>

    {% endif %}
{% else %}
    <div class="alert alert-danger" role="alert"><strong>You are not a registered client!</strong></div>

{% endif %}

{% endblock %}

templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

{% block body_block %}
     {% if msg %}
         {% if neg == 0 %}
            <div class="alert alert-success" role="alert"><h4>{{ msg }}</h4></div>
         {% else %}
            <div class="alert alert-danger" role="alert"><h4>{{ msg }}</h4></div>
         {% endif %}
    {% endif %}
{% endblock %}

templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if testuser.client %}
        {% if prodlist %}
            <h2>List of Products</h2>
            <ol>
                {% for pro  in prodlist %}
                    <li> {{ pro }}:  ${{ pro.price }} </li>
                {% endfor %}
            </ol>
        {% else %}
            <div class="alert alert-warning" role="alert">There are no available products!</div>
    {% endif %}
    <form method="post">
    {% csrf_token %}
        <div class="panel panel-success detailpanel">
        <table border="1" class="table">
            {{  form }}
        </table>
    <br>
    <button type="submit" class="btn btn-success loginbtn">Submit</button>
            </div>
    </form>
    {% else %}
    <div class="alert alert-danger" role="alert"><strong>You are not a registered client!</strong></div>

{% endif %}

{% endblock %}

templates/myapp/productdetail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
{% if prod %}
        <h2>Product: {{ prod }}</h2>
        <h2>People interested: {{ prod.interested }}</h2>

    <h2>Price: {{ prod.price }}</h2>
     <form method="post" class="proddetailthing">
        {% csrf_token %}

            <table border="1" class="table">
                {{ form }}
            </table>

         <button type="submit" class="btn btn-success loginbtn">  Submit </button>
    </form>
{% else %}
    <div class="alert alert-warning" role="alert">There are no available Products!</div>
{% endif %}
{% endblock %}

templates/myapp/products.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if prodlist %}
        <div class="panel panel-success detailpanel">
        <!-- Default panel contents -->
            <div class="panel-heading"><h3 class="panel-title">List of Products</h3></div>
            <!-- List group -->
            <ul class="list-group productsthing">
                {% for prod  in prodlist %}
                    <li> <a href="{% url 'myapp:product detail' prod.pk %}"> {{ prod.name}} </a></li>
                {% endfor %}
            </ul>
            <div class="panel-footer">
                <a href="{% url 'myapp:place_order' %}">Place new Order</a>
            </div>
        </div>
    {% else %}
        <div class="alert alert-warning" role="alert">There are no available Products!</div>
    {% endif %}
{% endblock %}

templates/myapp/register.html
{% extends 'myapp/base.html' %}

{% block body_block %}

<form method="post">
{% csrf_token %}

<div class="loginform">
    <div class="form-group">
    <label for="username">Username</label>
    <input type="text" class="form-control" name="username" id="username" aria-describedby="username2" placeholder="Enter username" required>

  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
  </div>
    <div class="form-group">
    <label for="company">Company</label>
    <input type="text" class="form-control" name="company" id="company" placeholder="Company" required>
  </div>
    <div class="form-group">
    <label for="shippingadd">Shipping address</label>
    <input type="text" class="form-control" name="shippingadd" id="shippingadd" placeholder="Shipping address" required>
  </div>
    <div class="form-group">
    <label for="city">City</label>
    <input type="text" class="form-control" name="city" id="city" placeholder="City" required>
  </div>
    <div class="form-group">
    <label for="prov">Province</label>
    <input type="text" class="form-control" name="prov" id="prov" placeholder="Province " required>
  </div>
    <button type="submit" class="btn btn-success loginbtn">Submit</button>
</div>



</form>



{% endblock %}